workdir: /mithril/Data/NGS/Aligned/150415_chicken # path to save the analysis outputs
codedir: /home/isac/Code/projects/chicken # path to this dir
reference: /mithril/Data/NGS/Reference/chicken/chicken6/Gallus_gallus.GRCg6a.dna_sm.toplevel.fa # path to reference genome
threads: 10 # available cores
