workdir: /mnt/c/Data # path to save the analysis outputs
codedir: /home/ubuntu/Code/chicken # path to this dir
reference: /mnt/c/Reference/chicken6/Gallus_gallus.GRCg6a.dna_sm.toplevel.fa # path to reference genome
threads: 72 # available cores
