workdir: /mithril/Data/NGS/projects/chicken # path to save the analysis outputs
codedir: /home/isac/Code/projects/chicken # path to this dir
reference: /mithril/Data/NGS/Reference/chicken/chicken6/Gallus_gallus.GRCg6a.dna_sm.toplevel.fa # path to reference genome
salmon_index: /mithril/Data/NGS/Reference/chicken/chicken6/Gallus_gallus.GRCg6a.cdna.all.salmon_index
threads: 10 # available cores
